@startuml

class Examenes{
    - String name
}

class Usuarios{
    - String username pk
    - String contrasena
    - String nombres
    - String apellidos
    - String email
    - String direccion
    - String tel_fijo
    - String tel_movil
    - Boolean active
    - Boolean admin
    +set()
    +get()

}

@enduml
