@startuml

class Seccion{
    - String nombre
    + void setNombre(String nombre)
    + String getNombre()

}

class Examen{
    - Long cups pk
    - String examen
    - Double valor
    - String descripcion
    - fk_SeccionNombre
    + set()
    + get()
}
Seccion "1" o-- "*" Examen

class Usuarios{
    - String username pk
    - String contrasena
    - String nombres
    - String apellidos
    - String email
    - String direccion
    - String tel_fijo
    - String tel_movil
    - Boolean active
    - Boolean admin
    +set()
    +get()

}

@enduml
